export enum MenuType {
    HOME = "HOME",
    SEARCH = "SEARCH",
    MOVIES = "MOVIES",
    SERIES = "SERIES",
    CATALOG = "CATALOG",
    MYLIST = "MYLIST",
    EDITION = "EDITION",
    PLUS = "PLUS",

    HISTORIC = "HISTORIC",
    PROFIL = "PROFIL",
    DOCUMENTATION = "DOCUMENTATION",
    USER_SUPPORT = "USER SUPPORT",
    PARAM_APPLI = "PARAM APPLI",
    META_DATA = "META DATA",
    MANAGEMENT_USER = "MANAGEMENT USER",

    MODIFY_NEWS_HOME = "MODIFY NEWS HOME",
    MODIFY_NEW_MOVIES = "MODIFY NEW MOVIES",
    MODIFY_NEW_SERIES = "MODIFY NEW SERIES",

    ADD_CATEGORY = "ADD CATEGORY",
    MODIFY_CATEGORY = "MODIFY CATEGORY",

    ADD_MOVIE = "ADD MOVIE",
    MODIFY_MOVIE = "MODIFY MOVIE",

    ADD_SERIES = "ADD SERIES",
    MODIFY_SERIES = "MODIFY SERIES",

    ADD_CREDIT = "ADD CREDIT",
    MODIFY_CREDIT = "MODIFY CREDIT",

    ADD_SELECTION = "ADD SELECTION",
    MODIFY_SELECTION = "MODIFY SELECTION",

    ADD_LICENSE = "ADD LICENSE",
    MODIFY_LICENSE = "MODIFY LICENSE",
    MODIFY_ORDER_LICENSE = "MODIFY ORDER LICENSE",

    MODIFY_HOME_PAGE_SELECTION = "MODIFY HOME PAGE SELECTION",
    PARAM_JELLYFIN = "PARAM JELLYFIN",
    VERSION = "VERSION",
    LIBRARY = "LIBRARY"
}